site_name: Docs
# site_url:
repo_name: idmp-toolkit
repo_url: https://git.cdplab.org/ericmonzon/idmp-toolkit

theme: 
  name: material
  favicon: assets/icon.svg
  icon:
    logo: simple/readthedocs
    repo: simple/gitea
  palette: 
  # dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple

    # light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: deep purple
      accent: deep purple

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search
  - mkdocstrings

nav:
  - "Home": index.md
  - "Getting Started": "getting_started.md"
  - "Modules":
    - "preprocess": modules/preprocess.md
  - "Contributing": "contributing.md"

extra:
  generator: false